ui: tape
browsers:
  - name: chrome
    version: [27,30,33,latest]
    platform: [Windows 8.1,Windows 8,Windows 7,Windows XP,OS X 10.6,OS X 10.8,OS X 10.9,OS X 10.10,Linux]

  - name: firefox
    version: [4,5,6,7,8,9,10,latest]
    platform: [Windows 8.1,Windows 8,Windows 7,Windows XP,OS X 10.6,OS X 10.9,OS X 10.10,Linux]

  - name: safari
    version: 5..latest

  - name: ie
    version: 6..latest

  - name: opera
    version: latest
    platform: [Windows 8.1,Linux]

  - name: android
    version: 4.0..latest

  - name: ipad
    version: 4.3..latest

  - name: iphone
    version: 4.3..latest