ui: tape
browsers:
  - name: chrome
    version: [27,38]
    platform: ["Windows 2012 R2","Windows 2012","Windows 2008","Windows 2003","Mac 10.6","Mac 10.8","Mac 10.9","Mac 10.10","Linux"]

  - name: firefox
    version: [4,33]
    platform: ["Windows 2012 R2","Windows 2012","Windows 2008","Windows 2003","Mac 10.6","Mac 10.8","Mac 10.9","Mac 10.10","Linux"]

  - name: safari
    version: 5..latest

  - name: ie
    version: 6..latest

  - name: opera
    version: latest
    platform: ["Windows 2012 R2","Linux"]

  - name: android
    version: 4.0..latest

  - name: ipad
    version: [5.1,6.1,7.1,latest]

  - name: iphone
    version: [5.1,6.1,7.1,latest]